version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: save_sync
      POSTGRES_USER: save_sync
      POSTGRES_PASSWORD: save_sync
    volumes:
      - ./tmp/database:/var/lib/postgresql/data
